### PR TITLE
fixed build errors

### PR DESCRIPTION
**Pull request by bublick**
- fixed getJson
- fixed isMultilangual

### CODE REVIEW

**Comment by urish** [comment]
Hi, what build errors did you get?

**Comment by bublick** [comment]
> Hi, what build errors did you get?

Hi @urish ! Errors appear on new Hugo versions.

**Comment by urish** [comment]
Thanks, I can see now:

```
hugo v0.139.0-dacef0df92a9a20072b4eaa42003e1a63ace8f41 windows/amd64 BuildDate=2024-11-18T16:17:45Z VendorInfo=gohugoio

ERROR deprecated: data.GetJSON was deprecated in Hugo v0.123.0 and will be removed in Hugo 0.140.0. use resources.Get or resources.GetRemote with transform.Unmarshal.
ERROR deprecated: .Site.IsMultiLingual was deprecated in Hugo v0.124.0 and will be removed in Hugo 0.140.0. Use hugo.IsMultilingual instead.
Total in 3065 ms
```

**Comment by urish** [comment]
I removed the design-tt02 shortcode (it's no longer being used), and the design-tt01 shortcode may be out of the door soon (it's only used it https://www.tinytapeout.com/digital_design/ which could definitely use a refresh).

The menu.html / search.html are just overriding the same files from the learn theme, right?

**Comment by bublick** [comment]
yes, with overrides, to save the theme origin

**Comment by urish** [comment]
Awesome, thanks!

**Pull request merged**
